# Generated by Django 2.2.6 on 2019-10-26 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_student_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='owner',
        ),
    ]
